resources/asia/taiwan/OSM-TW-facebook.json
added OSM-TW facebook group info
=> Added OSM-TW facebook group info

i18n/en.yaml, resources/europe/be/be-meetup.json
=> Added meetup page of OSM BE

i18n/en.yaml, resources/asia/india/osm-india-facebook.json
Referring to https://github.com/osmlab/osm-community-index/commit/895869a73f096b7a544be4a283d813e9573f78f5#commitcomment-28628492
Added the State of the Map Asia 2018 event to the resources in India. Let me know if works, thank you! 
cc: @bhousel @govvin
=> Adding SotM Asia to the resources

CONTRIBUTING.md
It is a bit silly when the _tl;dr_ is larger than the long explanation :-)
=> Reorder geojson part in documentation

resources/asia/japan/OSM-Japan-website.json
OpenStreetMap Japan website added to Resource
=> add Japan OpenStreetMap Website

resources/europe/be/be-matrix.json, resources/europe/be/be-meetup.json, resources/europe/be/be-twitter.json
- Fix `featureId`
- Update some links and descriptions
=> Update Belgium resources

resources/asia/bangladesh/osm-bangladesh-facebook.json
So https://community.osmbe.akoo.ovh/resources/asia/bangladesh would work properly
=> Correcting {Url} to {url}

resources/asia/korea/OSM-korea-telegram.json
Fixing my own email address should be uncontroversial!
=> Fix email address for OSM-Korea-Telegram channel's contact

i18n/en.yaml, i18n/ru.yaml, resources/world/OSM-IRC.json
=> Add link to IRC channel

resources/europe/denmark/dk-irc.json, resources/europe/finland/fi-irc.json, resources/europe/france/fr-irc.json, resources/europe/germany/de-irc.json, resources/europe/italy/it-irc.json, resources/europe/sweden/se-irc.json, resources/europe/united_kingdom/uk-irc.json, resources/south-america/argentina/OSM-AR-irc.json
replaced   irc.openstreetmap.org with https://webchat.oftc.net/?channels=osm
=> Fix #136, replaced urls

schema/resource.json
Ref https://github.com/osmlab/osm-community-index/issues/200
Support new channel types: homepage, github, youtube, wiki.
=> Add types: homepage, github, youtube, wiki

resources/asia/osm-asia-mailing-list.json, resources/asia/osm-asia-telegram.json
updated mailing list and telegram group of Asia community
=> OSM Asia community

package.json
=> chore(package): update tap to version 14.0.0

CONTRIBUTING.md, resources/oceania/australia/geogeeks_perth
Per feedback from @quincylvania in https://github.com/osmlab/osm-community-index/pull/243
=> Update GeoGeeks Perth and clarify doco for the 'meetup' group type

i18n/en.yaml, resources/north-america/nicaragua/ni-facebook.json, resources/north-america/nicaragua/ni-mailinglist.json, resources/north-america/nicaragua/ni-telegram.json, resources/north-america/nicaragua/ni-twitter.json, resources/north-america/nicaragua/osm-ni.json
This PR adds community resources for Nicaragua obtained from their [wiki page](https://wiki.openstreetmap.org/wiki/ES:Nicaragua#Comunidad_y_colaboradores)
=> add nicaragua resources

resources/asia/south_korea/OSM-KO-mailinglist.json
please include the mailinglist for Korea
=> added talk-ko mailinglist

i18n/en.yaml, resources/asia/bangladesh/osm-bangladesh-facebook.json
Added the State of the Map Asia 2019 event to the resources
=> add SotM Asia 2019

features/europe/ireland/ireland.geojson, i18n/en.yaml, resources/europe/ireland/ireland-facebook.json, resources/europe/ireland/ireland-irc.json, resources/europe/ireland/ireland-mailinglist.json, resources/europe/ireland/ireland-telegram.json, resources/europe/ireland/ireland-twitter.json
=> Add OSM Ireland resources

resources/europe/poland/OSM-PL-forum.json
this is a de facto place for OSM community in Poland
=> bump OSM pl forum priority

resources/europe/hungary/hu-matrix.json
=> Add Europe/Hungary Matrix room

resources/europe/bulgaria/bg-forum.json, resources/europe/bulgaria/bg-wiki.json
Added resources for the only 2 community resources I'm aware of for Bulgaria, namely the forum and the Wikiproject page.
I'm a regular mapper in Bulgaria ([saintam1](http://www.openstreetmap.org/user/saintam1)).
=> Add resources for Bulgaria

resources/europe/kosovo/kosovo-matrix.json, resources/europe/kosovo/kosovo-telegram.json
Hey,
this PR contains the necessary files to add the Matrix Channel "OpenStreetMap Kosovo". The Telegram and the Matrix ones are connected, so you can interact with the one on Telegram by joining the one in Matrix and vis versa.
=> Adding Matrix Kosovo group

resources/africa/south_africa/osm-za-twitter.json, resources/africa/south_africa/talk-za.json
Add South Africa twitter + mailinglist.
=> Add South Africa twitter + list

i18n/en.yaml, resources/world/OSMF.json
=> Add SoTM2020. Fix #319

resources/europe/croatia/hr-forum.json, resources/europe/croatia/hr-mailinglist.json, resources/europe/croatia/hr-wiki.json, resources/europe/croatia/osm-hr.json
add wiki, forum, web, and fix mailinglist
=> Add more croatia community channels

resources/europe/malta/mt-irc.json
In this pull request, I propose adding the IRC channel for mappers working on Malta.
=> Add Malta OSM IRC

resources/europe/germany/de-matrix.json
Use short link for consistency as suggested by @jbelien in #376 .
=> Use short link for german matrix room

resources/europe/poland/OSM-PL-telegram
I have not run `npm run test` as I don't have Node installed - thanks for doing this.
=> Adding OSM Poland Telegram group

resources/middle-east/iran/osm-iran-discord.json
Add the OpenStreetMap Iran Discord, as from https://wiki.openstreetmap.org/wiki/Discord_servers
=> Add OSM Iran Discord

CONTRIBUTING.md
include it in tldr as it is not obvious for everybody (hello me)
and node error generated without it is not very clear
=> mention npm install for node newbies

resources/europe/germany/de-berlin-matrix.json
We  created a new Matrix room for our local community to switch over from telegram.
=> Adding new Matrix Berlin Chat

resources/africa/cameroon/talk-cm.json
Added a talk list to Cameroon via personal fork
=> Cameroon talk list addition

resources/europe/luxembourg/lu-github.json, resources/europe/luxembourg/lu-irc.json, resources/europe/luxembourg/lu-mailinglist.json, resources/europe/luxembourg/lu-matrix.json
Hi,
When I created the resources, I misunderstood the property `order`.
This PR fixes the order and improves the description for our resources :)
=> Reordered and improved descriptions for resources in Luxembourg

resources/africa/algeria/osm-dz-forum.json, resources/asia/afghanistan/osm-afghanistan-mailinglist.json, resources/europe/albania/al-facebook.json, resources/europe/albania/al-forum.json, resources/europe/albania/al-maptime-tirana.json, resources/europe/albania/al-talk.json, resources/europe/albania/al-telegram.json, resources/europe/albania/al-twitter.json
Added a mailing list to the already created comms group for Afghanistan
=> added a talk list to the afghanistan comms channels

resources/asia/azerbaijan/osm-azerbaijan-facebook.json, resources/asia/bangladesh/osm-bandladesh-forum.json, resources/asia/bangladesh/osm-bangladesh-facebook.json, resources/asia/bangladesh/osm-bangladesh-talk.json, resources/asia/bangladesh/osm-bangladesh-telegram.json, resources/europe/belarus/by-facebook-osm.json, resources/europe/belarus/by-forum-osm.json, resources/europe/belarus/by-talk-osm.json, resources/europe/belarus/by-telegram-osm.json
added a Facebook page for the country of Azerbaijan
=> azerbaijan

resources/africa/algeria/osm-dz-forum.json, resources/africa/benin/osm-benin-facebook.json, resources/africa/benin/osm-benin-talk.json, resources/africa/benin/osm-benin-telegram.json, resources/africa/benin/osm-benin-twitter.json, resources/europe/bosnia_herzegovina/OSM-BiH-Facebook.json, resources/europe/bosnia_herzegovina/OSM-BiH-Forum.json, resources/europe/bosnia_herzegovina/OSM-BiH-Talk.json, resources/europe/bosnia_herzegovina/OSM-BiH-telegram.json, resources/south-america/bolivia/OSM-BO-Telegram.json
Revised and added comms to Benin, Bolivia, and Bosnia and Herzegovina
=> Comms Additions

resources/africa/burkina_faso/bf-talk-osm.json, resources/africa/burundi/bi-talk-osm.json, resources/africa/burundi/bi-twitter.json, resources/asia/cambodia/kh-facebook-osm.json, resources/asia/cambodia/kh-forum-osm.json, resources/asia/cambodia/kh-twitter.json, resources/europe/bulgaria/bg-facebook-osm.json, resources/south-america/brazil/OSM-br-discord.json, resources/south-america/brazil/OSM-br-forum.json, resources/south-america/brazil/OSM-br-mailinglist.json, resources/south-america/brazil/OSM-br-telegram.json, resources/south-america/brazil/OSM-br-twitter.json
This PR includes additions and revisions to Comms links for Brazil, Bulgaria, Burkina Faso, Burundi, and Cambodia.
=> Country Comms Updates and Additions

.gitignore, CONTRIBUTING.md, package.json, scripts/build_local.js
Created "npm run local" in packages.json, created a corresponding script and described the process in CONTRIBUTING.md
=> Add run locally contribution

resources/europe/albania/al-telegram.json, resources/north-america/cuba/OSM-CU-telegram.json, resources/north-america/guatemala/guatemala-telegram.json, resources/north-america/nicaragua/ni-telegram.json, resources/north-america/panama/panama-telegram.json, resources/south-america/argentina/OSM-AR-telegram.json, resources/south-america/bolivia/OSM-BO-Telegram.json, resources/south-america/colombia/OSM-CO-telegram.json, resources/south-america/ecuador/OSM-EC-telegram.json, resources/south-america/paraguay/OSM-PY-telegram.json, resources/south-america/peru/OSM-PE-telegram.json, resources/south-america/venezuela/ve-telegram.json
Shortening Telegram URLs from `telegram.me/*` to `t.me/*`
=> Shortening Telegram URLs

resources/asia/indonesia/id-facebook-osm.json, resources/asia/indonesia/id-forum-osm.json, resources/asia/indonesia/id-talk-osm.json, resources/asia/indonesia/id-telegram-osm.json, resources/asia/indonesia/id-twitter-osm.json, resources/europe/iceland/is-chapter.json, resources/europe/iceland/is-forum-osm.json, resources/europe/iceland/is-mailinglist.json, resources/europe/iceland/is-twitter.json, resources/south-america/honduras/hn-talk-osm.json
Added and edited comms lists for Iceland, Indonesia, and Honduras
=> Country Update

resources/europe/slovakia/sk-mailinglist.json, resources/europe/spain/MapColabora-mailinglist.json, resources/europe/switzerland/ch-mailinglist.json, resources/south-america/argentina/OSM-AR-mailinglist.json, resources/south-america/bolivia/OSM-BO-mailinglist.json, resources/south-america/brazil/OSM-br-mailinglist.json, resources/south-america/chile/OSM-CL-mailinglist.json, resources/south-america/colombia/OSM-CO-mailinglist.json, resources/south-america/peru/OSM-PE-mailinglist.json
=> HTTPs'ing, archive to listinfo and Google Groups URL update

resources/north-america/panama/pa-forum.json, resources/north-america/panama/pa-telegram.json, resources/north-america/panama/ym-University-of-Panama.json
I've explicit set `order` to the default value `0` for the YMUP Chapter, `10` for the official forum, and `5` for the local Telegram group. This is based on my experience, after having spent 4½ years in this country.
=> explicit order for Panamanian communities

resources/europe/netherlands/nl-mailinglist.json, resources/europe/netherlands/nl-wonderme.json
Added the Dutch mailing list and virtual meeting room Wonder.me
=> Add Dutch mailing list and Wonder.me

resources/asia/india/kerala/osm-kerala-github.json
Adding osmkerala github account
=> + osmkerala github

resources/europe/france/fr-xmpp.json, resources/europe/germany/de-xmpp.json
Added XMPP for Germany, Updated XMPP FR URL with ?join so that Gajim (and others) will understand the Address to be a joinable group rather than a single contact.
=> XMPP: Add DE (National), Update FR (National)

resources/europe/ireland/ireland-matrix.json, resources/europe/ireland/ireland-youtube.json
Adding two more resources for the OSM Ireland community.
=> OSM Ireland - Add links for matrix.org (bridge to IRC) and YouTube channel.

resources/asia/japan/OSM-Japan-slack.json
The slack URL has been updated.
So, it would be great if you could update the index as well.
=> Update Asia/Japane Slack invitation url

resources/africa/ghana/cape-coast-youthmappers.json, resources/africa/ghana/osm-gh-facebook.json, resources/africa/ghana/osm-gh-telegram.json, resources/africa/ghana/osm-gh-twitter.json, resources/africa/ghana/talk-gh.json, resources/africa/ghana/ym-University-of-Mines-and-Technology.json
Updated contacts for various channels in Ghana
=> Update Ghana channels contacts

resources/africa/nigeria/ym-Ignatius-Ajuru-University-of-Education.json, resources/africa/nigeria/ym-University-of-Nigeria-Nsukka.json, resources/north-america/mexico/mx-facebook.json, resources/north-america/united_states/ym-State-University-of-New-York-Geneseo.json, resources/north-america/united_states/ym-Western-Michigan-University.json, resources/world/OSM-Discourse.json
- Changed `fb.me` URLs to `https://www.facebook.com/`.
- Changed HTTP Facebook URLs to use HTTPS.
- Added WWW `www.` to Facebook URLs.
=> Upgrade URL

resources/europe/belgium/be-newsletter
I'm not sure you can work with this, there does not seem to be any newsletter in the repo yet. I'm not sure how many local communities have one; there's obviously the OSM weekly that could be included in the global section.
=> Resource for the newsletter

resources/europe/ireland/ireland-discourse.json
Add link to new OSM Ireland category on https://community.openstreetmap.org/
=> add discourse resource for Ireland

resources/asia/thailand/th-community-discourse.json
see https://community.openstreetmap.org/t/thailand-subcategory/2371/9
=> add community discourse subcategory for Thailand

resources/north-america/united_states/ym-Ball-State-University.json
see https://en-gb.facebook.com/Gamma-Theta-Upsilon-Iota-Omega-Chapter-249276948442687/
=> minor name tweak

.github/workflows/build.yml
Update to:
* actions/checkout@v3
* actions/setup-node@v3
=> Update GHA action to latest release

.github/dependabot.yml
Have dependabot suggest github action updates weekly.
=> Allow dependabot to update action

resources/europe/slovenia/si-github.json
Adds https://github.com/openstreetmap-si
=> Add Slovenian GitHub

resources/europe/slovenia/si-ljubljana-wiki.json, resources/europe/slovenia/si-wiki.json
Adds:
* https://wiki.openstreetmap.org/wiki/Slovenia
* https://wiki.openstreetmap.org/wiki/Ljubljana
=> Add Slovenian wiki pages

defaults.json, i18n/en.yaml, resources/europe/belgium/be-mastodon.json, schema/resource.json, scripts/build_icons.js, scripts/build_index.js
Hi,
With Mastodon taking off, I wanted to add the Belgian Mastodon account, but support seemed to be missing.
I did a best effort to add the support for this where needed, but I probably forgot something somewhere; so a thorough review would be welcome.
=> Add mastodon support, add mastodon for Belgium

resources/africa/benin/osm-benin-telegram.json
=> Benin telegram disappeared

resources/africa/kenya/ym-University-of-Nairobi.json
fixes #624
maybe https://www.facebook.com/GesaUon should be linked directly?
=> attempt to fix link

resources/asia/korea/ko-discourse.json, resources/asia/korea/ko-facebook.json, resources/asia/korea/ko-forum.json, resources/asia/korea/ko-github.json, resources/asia/korea/ko-matrix.json, resources/asia/korea/ko-osm.json, resources/asia/korea/ko-telegram.json, resources/asia/korea/ko-twitter.json, resources/asia/korea/kp-wiki.json
* Discourse: https://community.openstreetmap.org/c/communities/ko
* Twitter: https://twitter.com/OSM_Korea
* Homepage: https://osm.kr
* Matrix: #OpenStreetMapKorea:Matrix.org
=> add some communties for South Korea

resources/europe/armenia/am-telegram.json
Hi folks,
This PR is to mention the Telegram channel of OSM Armenia.
I haven't found any other Armenian mappers' communities, so let's get the ball rolling.
=> Add OSM Armenia Telegram

resources/asia/malaysia/my-telegram.json
Hi all,
This PR is to add OSM Malaysia Telegram group.
Thanks.
=> Add OSM Malaysia Telegram

resources/asia/pakistan/pk-facebook.json
The previous group link doesn't seem to work, but searching on facebook now finds this group which currently has 75 members
=> Update Pakistan Facebook

resources/europe/switzerland/ch-mailinglist.json
The operator of the mailing list seems to have updated the software and the URL.
=> Seems as if maillig list URL has changed

resources/europe/montenegro/mne-telegram.json
=> Add community for Montenegro

resources/asia/iraq/iq-telegram.json
Added OSM Iraq group so editors in Iraq can reach the group and discuss and improve the map.
=> Added OSM Iraq Telegram links

resources/north-america/united_states/OSM-Utah.json
We no longer use meetup, changing to slack
=> Update OSM Utah

resources/europe/cyprus/cyprus-matrix.json
Added Cypriot Matrix chat to the community index. I do have Node installed but I couldn't really figure out how to use it tbh.
=> Added Cypriot Matrix chat

resources/world/OSM-Discord.json
=> Update languageCodes for OSM-Discord.json

resources/asia/vietnam/vn-telegram.json, resources/asia/vietnam/vn-wiki.json
Hello,
This is my third PR for the project. This time I address Vietnam:
- add the long existing but not yet listed here [wiki](https://wiki.openstreetmap.org/wiki/Vietnam),
- add the newly created telegram [chat](https://t.me/osm_vietnam).
=> Add OSM Vietnam Telegram and Wiki

resources/europe/switzerland/ch-discourse.json, resources/europe/switzerland/ch-mastodon.json
=> Add Swiss OSM Mastodon and Discourse

resources/asia/bangladesh/bd-discourse.json
No reordering of priorities, as seem to have been conciously set?
=> Add Bangladesh community forum

resources/europe/finland/fi-discourse.json
Downgrade email list to bottom that does not see real activity
=> Add Finland community forum

resources/europe/hungary/hu-discourse.json
Downgrade the Facebook page with last post in February. Keep the active Facebook group in current location
=> Add Hungary community forum

resources/asia/indonesia/id-discourse.json
Replace it with the top email list that has no posts since 2016 :)
=> Add Indonesia community forum
