osmlab/osm-community-index

- resources/europe/de/de-forum.json
- resources/europe/de/de-irc.json
- resources/europe/de/de-mailinglist.json
- resources/europe/de/osm-de.json
Even though FOSSGIS e.V., the official OSMF local chapter for Germany, is not the operator of the German Forum, Mailing List, or IRC channel, it sounds most sensible to list them as a contact address. They *are* the operator of openstreetmap.de.
> use info@fossgis.de (local chapter) as generic contact

- i18n/en.yaml
- resources/europe/be/be-irc.json
This fixes the IRC broken webinterface with the working OFTC official webinterface. It fixed the problem mentioned here : https://github.com/osmlab/osm-community-index/commit/15598db00be4621b73a5f4f247384ede5c11b644#commitcomment-28621809
> fix the OFTC IRC weblink - peer tested

- resources/europe/de/de-berlin-meetup.json
Change signupUrl to url. The current release points to meetup.com only, not to OSM-Berlin-Brandenburg
> Fix URL of Meetup Berlin

- i18n/en.yaml
- resources/europe/italy/it-telegram.json
This PR adds the OpenStreetMap Italy Telegram chat, which is also linked on the [Italian WikiProject page](https://wiki.openstreetmap.org/wiki/WikiProject_Italy).
> Add OpenStreetMap Italy Telegram

- build.js
Show also JSON.parse errors nicely when JSON is horribly broken instead of just dumping a stacktrace without pointing out which file is problematic.
Show progress & summary during Feature & Resource generation, eg:
```
building data
Features:✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓91
Resources:✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓180
data built: 246.582ms
```
> Show JSON parse errors & progress bar with summary

- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- resources/north-america/united_states/OSM-US-Slack.json
In the interest of relying less on Heroku, I'd like to change all these to point to openstreetmap.us domains.
> Update the OSM US Slack join URL

- resources/asia/india/osm-india-forum.json
- resources/asia/india/osm-india-github.json
- resources/asia/india/osm-india-telegram.json
- resources/asia/india/osm-india-website.json
- resources/asia/india/osm-india-wiki.json
- resources/asia/india/osm-india-youtube.json
- resources/asia/india/osm-puducherry-mailing-list.json
Added telegram,wiki,forum,website,youtube,github. Rearrange PU mailing list
> Update OSM IN

- resources/asia/north_korea/OSM-KO-mailinglist.json
- resources/asia/north_korea/OSM-korea-telegram.json
- resources/asia/south_korea/OSM-KO-mailinglist.json
- resources/asia/south_korea/OSM-korea-telegram.json
Both Mailinglist as well as Telegram group are covering South and North Korea. Please also allow me to note that North Koreans will be offended by refering their country as such. The proper term would be _Democratic People's Republic of Korea_ or _DPRK_.
> North and South Korea

- resources/europe/ukraine/ua-facebook.json
- resources/europe/ukraine/ua-forum.json
- resources/europe/ukraine/ua-github.json
- resources/europe/ukraine/ua-slack.json
- resources/europe/ukraine/ua-telegram.json
- resources/europe/ukraine/ua-twitter.json
- resources/europe/ukraine/ua-website.json
Fixed initially incorrectly submitted languageCodes "ua" for Ukrainian language. Should be "uk" instead.
> Corrected languageCodes ua->uk for Ukrainian

- features/south-america/brazil/riograndedosul.geojson
- resources/south-america/brazil/RS-telegram.json
This had been incorrectly defined as "rs" (Serbia).  Create a simple GeoJSON
enclosing it and change the definition of the Telegram group to use that.
> Fix location of Rio Grande do Sul

- resources/europe/kosovo/kosovo-matrix.json
This commit contains the updated url. We needed to close the previous one because that one was created by the portal bot. The OSM community shouldn't use groups that cannot be full controlled by the community. Previously I was just Moderator and not Owner. Communities have been/will be informed about the change.
> Matrix information for Kosovo community updated

- resources/asia/japan/OSM-Japan-slack.json
Slack workspace for Japanese mappers and users has been [set](https://twitter.com/osmfj/status/1243826444221865984).
I'd like  to add channel using this information.
Please let me know if you have any missing  information or wrong format.
Tested with `npm run test` on my env are here:
```
Suites:   1 passed, 1 of 1 completed
Asserts:  6 passed, of 6
Time:     6s
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |       30 |      100 |      100 |                   |
index.js |      100 |       30 |      100 |      100 |             2,3,4 | …
```
> Add Japan OpenStreetMap Slack workspace

- resources/africa/guinea/ym-General-Lansana-Conte-University.json
- resources/africa/kenya/ym-University-of-Nairobi.json
- resources/africa/mozambique/ym-Universidade-Eduardo-Mondlane.json
- resources/africa/rwanda/ym-Insititue-d-Enseignement-Superieur-de-Ruhengeri.json
- resources/africa/tanzania/ym-Institute-of-Rural-Development-Planning-Mwanza.json
- resources/asia/japan/OSM-Japan-slack.json
- resources/asia/nepal/ym-Kathmandu-University.json
- resources/north-america/united_states/ym-University-of-Northern-Colorado.json
Building the new static version of the OSM Community Index Viewer, I found out some URL where `http(s)://` is missing.
Warning: some URL's do not seem valid (404):
- http://www.geospatial.uonbi.ac.ke/
- https://www.facebook.com/Moz-YouthMappers
- https://ku.edu.np/ges (correct URL seems to be http://ges.ku.edu.np/)
> Add missing HTTP(S) to URL

- i18n/de.yaml
- i18n/en.yaml
- resources/europe/germany/de-berlin-xmpp.json
I've added the link to the Berlin and Brandenburg XMPP Multi-User Chat.
> Add XMPP-chat for Berlin / Germany

- resources/europe/germany/de-matrix.json
matrix.to links are the preferred and a more independent way to share rooms
> Use matrix.to link

- resources/europe/luxembourg/lu-github.json
- resources/europe/luxembourg/lu-irc.json
- resources/europe/luxembourg/lu-mailinglist.json
- resources/europe/luxembourg/lu-matrix.json
Hi,
This PR adds Matrix, IRC and GitHub for OSM Luxembourg :)
> Added OSM Luxembourg community

- resources/asia/india/osm-puducherry-matrix.json
- resources/asia/malaysia/OSM-MY-matrix.json
- resources/europe/greece/gr-matrix.json
- resources/europe/hungary/hu-matrix.json
- resources/europe/kosovo/kosovo-matrix.json
- resources/europe/luxembourg/lu-matrix.json
Following resources already use the Matrix link:
- Belgium (see #375)
- Germany: [`de-matrix.json`](https://github.com/osmlab/osm-community-index/blob/main/resources/europe/germany/de-matrix.json#L8)
- Peru: [`OSM-PE-matrix.json`](https://github.com/osmlab/osm-community-index/blob/main/resources/south-america/peru/OSM-PE-matrix.json#L8)
- Latam: [`latam-matrix.json`](https://github.com/osmlab/osm-community-index/blob/main/resources/world/latam-matrix.json#L8)
Germany Matrix link could be replaced by short version for consistency (ping @duncanturk)
Close #366
> Fix Matrix links

- resources/europe/united_kingdom/uk-localchapter.json
The OSM Local Chapter covers England, Scotland, Wales, Northern Ireland, the Channel Islands and Isle of Man. This change better reflects the region and has been tested on the Location Conflation test site:
The change:
https://ideditor.github.io/location-conflation/?locationSet=%7B%20include%3A%20%5B%22GB-ENG%22%2C%20%22GB-NIR%22%2C%20%22GB-SCT%22%2C%20%22GB-WLS%22%2C%20%22JE%22%2C%20%22GG%22%2C%20%22IM%22%5D%7D
Note that this is the same as ["GB-ENG", "GB-NIR", "GB-SCT", "GB-WLS", "830", "833"] but I have used ["GB-ENG", "GB-NIR", "GB-SCT", "GB-WLS", "JE", "GG", "IM"] rather than mixing ISO alpha codes with UN M49 numbers.
The original:
https://ideditor.github.io/location-conflation/?locationSet=%7B%20include%3A%20%5B%22GB%22%5D%7D%0A
FWIW the region shown for ISO code GB is likely to be …
> Correct region of UK local chapter

- resources/world/OSM-Discord.json
The Discord server is called "OpenStreetMap World".
> Correct OSM World server name

- resources/europe/germany/de-telegram.json
telegram/OSM_de is now called "OSM D-A-CH" (for Germany, Austria and Switzerland) - added at and ch to the locationSet.
> telegram/OSM_de is now called "OSM D-A-CH"

- resources/world/OSM-Discord.json
The OSM World Discord recently got a vanity URL, this updates the index to the vanity invite ID from the old invite ID.
The old invite ID still works (for now), but it's best to change it.
> Update OSM World Discord to the new vanity URL

- resources/south-america/colombia/Maptime-Bogota.json
This is a small change for the MaptimeBogota group
> MaptimeBogota updated

- scripts/build_index.js
When the area in a geoJSON file is smaller than 2000 km², the build script warns and suggests to use a circular include rather than the (probably) larger geoJSON file.
With this PR, the warning will also calculate and show a diameter that should include all the maximum extents of the file.
> Improve small area warning

- defaults.json
Add WWW `www.` to websites which redirect to it by default (on mobile, this will automaticly be converted to a mobile view link if present, see ie. Facebook).
> Upgrade default

- resources/world/OSMF.json
OpenStreetMap is typically not written with the article _“the”_. This changes wording in the sentence to _“the OpenStreetMap project”_ instead to fix the grammar.
> Don't write _the_ OpenStreetMap

- resources/north-america/belize/ym-Sacred-Heart-Junior-College.json
> fix spelling of "YouthMappers"

- resources/europe/slovenia/si-discourse.json
> Add Slovenian discourse category

- resources/europe/austria/at-mastodon.json
I added the config file for the Austrian Mastodon account by copying and modifying the one from europe/belgium .
> add Mastodon account for OpenStreetMap Austria

- resources/africa/south_africa/OSM-ZA-discourse.json
Add South African Discourse community: https://community.openstreetmap.org/c/communities/za
Small but improve visibility to South African mappers.
> Add Discourse South Africa

- resources/europe/italy/it-chapter.json
The Italian local chapter of OSMF, Wikimedia Italia, created a new website dedicated to the Italian OSM community. The link is now fixed and more specific with respect to the previous one
> fix link to new website for italian comunity

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- resources/africa/congo/cd-chapter.json
- resources/africa/ghana/ym-University-of-Mines-and-Technology.json
- resources/africa/guinea/ym-General-Lansana-Conte-University.json
- resources/africa/south_africa/ym-University-of-Pretoria.json
- resources/europe/albania/al-maptime-tirana.json
- resources/europe/ukraine/ua-slack.json
- resources/europe/united_kingdom/uk-mappamercia.json
- resources/middle-east/turkey/YerCizenler-TR.json
- resources/north-america/united_states/ym-Clemson-University.json
- resources/north-america/united_states/ym-University-of-Oregon.json
- resources/north-america/united_states/ym-University-of-Wyoming.json
- resources/north-america/united_states/ym-Vassar-College.json
- resources/south-america/argentina/OSM-AR-geolibres.json
- resources/south-america/peru/OSM-PE.json
I noticed today on openstreetmap.org that some chapter links were not using `https`, so I made some investigations. This PR updates all of the resources and documentation that used `http` to use `https`, where:
* The `http` version redirects to `https` (checked with `curl -I`, received a 301 or 302 response) - that was most of them, or
* The `http` version doesn't redirect, but serves the same content as the `https` version ( https://www.uwyo.edu/geography/geographyclub/ and https://bit.ly/SlackOsmUa )
There were two resources that I didn't update, since they need further investigation:
* resources/africa/nigeria/ym-Federal-University-of-Technology-Akure.json:9:    "url": "http://spaceclubfuta.com.ng/" - domain not found
* resources/asia/bangladesh/ym-Asian-University-for-Women.json:9: …
> Use https for resources and documentation.

- resources/europe/poland/OSM-PL-discourse.json
Discussed on https://community.openstreetmap.org/t/to-forum-vs-grupa-fb-vs-discord-na-panelu-po-edycji-w-id/8666 and was announced on https://discord.com/channels/783754873861963786/783763382201352272/1072199854060740738 (OSM PL Discord which has heavy activity)
> official forum for OSM PL community: on top

- resources/middle-east/turkey/tr-telegram.json
This reverts commit 5cc17a681f4ca1e238a08e1643944a8041bd9305.
Apparently it was some hiccup/mistake/temporary state/Telegram bug and can be accessed per https://github.com/osmlab/osm-community-index/issues/641#issuecomment-1427133677 (but I have not verified it)
fixes #641
(note: my node is not recent enough per https://github.com/osmlab/osm-community-index/blob/main/package.json#L87 to run `npm run test` mentioned in https://github.com/osmlab/osm-community-index/wiki/Contributing)
> Revert "Remove OpenStreetMap Türkiye telegram group, requires payment"

- dist/resources.json
- i18n/en.yaml
- resources/north-america/united_states/Code-for-San-Jose-Discord.json
- resources/north-america/united_states/Code-for-San-Jose-Slack.json
Code for San José is using a Discord server in addition to its Slack workspace. There’s an OSM channel on both. Also, the organization brands itself with an accent mark.
/ref codeforsanjose/OSM-SouthBay#40
> Code for San José Discord

- resources/europe/switzerland/sosm.json
The Swiss local chapter was missing an entry.
> Add entry for SOSM

- resources/asia/singapore/sg-telegram.json
- resources/asia/singapore/sg-wiki.json
- resources/europe/armenia/am-wiki.json
I created osm_armenia Telegram group back in 2022 when I lived there. Now I'm going to visit Singapore and I'm really surprised there is no chat/group for this country. Let's create one. I have just updated the corresponding [wiki page](https://wiki.openstreetmap.org/wiki/List_of_OSM_centric_Telegram_accounts).
This commit also adds links to the existing OSM wiki pages for Armenia and Singapore.
> Add OSM Singapore Wiki and Telegram, OSM Armenia Wiki

- resources/europe/portugal/pt-discord.json
- resources/europe/portugal/pt-discourse.json
- resources/europe/portugal/pt-telegram.json
- resources/europe/portugal/pt-wiki.json
- resources/south-america/brazil/br-discord.json
- resources/south-america/brazil/br-discourse.json
- resources/south-america/brazil/br-telegram.json
- resources/south-america/brazil/br-twitter.json
- resources/south-america/brazil/br-wiki.json
- resources/south-america/brazil/talk-br.json
Hey guys!
Local community asked, and also based on my experience, I'm trying to fix the order of elements, both in Portugal and Brazil. In Brazil I also added the missing wiki page.
(Sorry for many commits, I had wrongly understood the 'order' value so had to redo everything hehe).
Please let me know if there's anything else to be done or fixed.
> Improved PT and BR order and added BR wiki

- resources/europe/germany/de-mainz-mailinglist.json
Fixup for #707, thanks @moschlar and @bhousel for the initial addition and review :heart: 
Currently wrong mailing list url: https://lists.openstreetmap.org/listinfo/mainz (org)
Correct mailing list url: https://lists.openstreetmap.de/listinfo/mainz (de)
Preview: https://openstreetmap.community/?map=49.79900,8.31769&zoom=8.87
I used Stuttgart as a template: https://github.com/osmlab/osm-community-index/blob/a85e277e5bdf009f8c63d736192acacb3c62d8c1/resources/europe/germany/de-stuttgart-mailinglist.json#L7-L11
> Fix mailinglist url for mainz

- resources/north-america/united_states/MapLYH.json
MapLYH has a small Signal group where we communicate to coordinate mapping, organize surveys, and discuss best practices. This commit adds MapLYH and a link to the Signal group to the map.
> Add MapLYH Signal group for Lynchburg, Virginia, USA

- resources/europe/cyprus/cyprus-matrix.json
Update to the wikidata tag in order to encompass the entire island, instead of just the Republic of Cyprus controlled portion; therefore incluidng RoC, TRoNC and British sovereign bases.
> Update cyprus-matrix.json to encompass entirety of the island

- resources/asia/japan/OSM-Japan-discord.json
The Japanese community has opened a Discord channel as a new chat platform.
Consequently, the Slack channel will be deprecated.
> add Discord channel for Japanese community

- dist/resources.json
- resources/europe/germany/de-berlin-mastodon.json
- Adding osmberlin Mastodon Account
- Removing telegram, channel will be removed in future currently only spam on it.
> Add Mastodon osmberlin, remove telegram

- resources/africa/osm-africa-discourse.json
- resources/africa/osm-africa-eventbrite.json
- resources/africa/osm-africa-facebook-group.json
- resources/africa/osm-africa-facebook.json
- resources/africa/osm-africa-matrix.json
- resources/africa/osm-africa-slack.json
- resources/africa/osm-africa-telegram.json
- resources/africa/osm-africa-twitter.json
Reprioritise other entries:
Chat-channels seem quite active, with more than thousand members in Matrix
Facebook group has no entries last month
Facebook account, Twitter and Eventbrite on bottom, given only being information channels
Mailing list has almost no real activity, mostly spam from the weeklyOSM newsletter
Part of effort to add all remaining community forums to the index, as not all communities are aware of this repository: https://community.openstreetmap.org/t/add-all-community-forums-to-the-community-index/119315
> Add Africa community forum

- resources/north-america/canada/OSM-CA-matrix.json
- resources/north-america/canada/ca-discourse.json
Matrix chat missing .json file ending, so not currently included. Only 3 members, so putting on bottom
Mailing list has some, but low activity so placing second last
> Add Canada community forum

- resources/europe/croatia/hr-discourse.json
- resources/europe/croatia/hr-mailinglist.json
Currently recommended Facebook don't have too much activity, so placing community forum on top
Mailing list not used since 2023, so pushing to bottom
Link to IRC is dead for me, but not an IRC expert
> Add Croatia community forum

- resources/europe/italy/it-facebook.json
No posts since 2023, so the default order applied in commit 75d2f15 is no longer good
> Remove Italy Facebook prioritization

- resources/europe/estonia/ee-discourse.json
- resources/europe/estonia/ee-wiki.json
- resources/europe/estonia/talk-ee.json
Language code for Estonian (et) is different from country code for Estonia (ee).
These projects are associated to Estonian (et) language not Ewe (ee) language.
> Fix language code for Estonian projects
